#coding:utf-8
class Image:
    def __init__(self):
        #各种图片
        self.Surface='jspvz/main_image/Surface.png'
        self.PlayGame1 = 'jspvz/main_image/PlayGame1.png'
        self.PlayGame2 = 'jspvz/main_image/PlayGame2.png'
        self.background1='jspvz/main_image/background1.jpg'
        self.SeedBank='jspvz/main_image/SeedBank.png'
        self.SunFlower='jspvz/main_image/SunFlower.png'
        self.SunFlowerfb = 'jspvz/main_image/SunFlowerfb.png'
        self.Sun='jspvz/main_image/Sun.gif'
        self.SunFlower1='jspvz/main_image/SunFlower1.gif'
        self.PeaShooter='jspvz/main_image/PeaShooter.png'
        self.PeaShooterfb = 'jspvz/main_image/PeaShooterfb.png'
        self.Peashooter1='jspvz/main_image/Peashooter.gif'
        self.ProjectilePea='jspvz/main_image/ProjectilePea.png'
        self.Zombiez1='jspvz/main_image/Zombiez/Zombiez-1.png'
        self.ZombieDie='jspvz/main_image/ZombieDie.gif'
        self.game_resume_nor='jspvz/main_image/game_resume_nor.png'
        self.game_pause_nor='jspvz/main_image/game_pause_nor.png'
        self.blhx='jspvz/main_image/blhx.jpg'
        self.Shovel='jspvz/main_image/Shovel.png'
        self.ZombiesWon='jspvz/main_image/ZombiesWon.png'
        self.WallNut='jspvz/main_image/WallNut.png'
        self.WallNutfb='jspvz/main_image/WallNutfb.png'
        self.WallNut1='jspvz/main_image/WallNut.gif'
        self.Wallnut_cracked1='jspvz/main_image/Wallnut_cracked1.gif'
        self.Wallnut_cracked2='jspvz/main_image/Wallnut_cracked2.gif'
        self.LargeWave='jspvz/main_image/LargeWave.gif'
        #1.弄一个列表2.从列表取出图片3.加载图片
        #轻装僵尸
        self.Zombiez_list=['jspvz/main_image/Zombiez/Zombiez-1.png',
                           'jspvz/main_image/Zombiez/Zombiez-3.png',
                           'jspvz/main_image/Zombiez/Zombiez-4.png',
                           'jspvz/main_image/Zombiez/Zombiez-5.png',
                           'jspvz/main_image/Zombiez/Zombiez-6.png',
                           'jspvz/main_image/Zombiez/Zombiez-7.png',
                           'jspvz/main_image/Zombiez/Zombiez-8.png',
                           'jspvz/main_image/Zombiez/Zombiez-9.png',
                           'jspvz/main_image/Zombiez/Zombiez-10.png',
                           'jspvz/main_image/Zombiez/Zombiez-11.png',
                           'jspvz/main_image/Zombiez/Zombiez-12.png',
                           'jspvz/main_image/Zombiez/Zombiez-13.png',
                           'jspvz/main_image/Zombiez/Zombiez-14.png',
                           'jspvz/main_image/Zombiez/Zombiez-15.png',
                           'jspvz/main_image/Zombiez/Zombiez-16.png',
                           'jspvz/main_image/Zombiez/Zombiez-17.png',
                           'jspvz/main_image/Zombiez/Zombiez-18.png',
                           'jspvz/main_image/Zombiez/Zombiez-19.png',
                           'jspvz/main_image/Zombiez/Zombiez-20.png',
                           'jspvz/main_image/Zombiez/Zombiez-21.png',
                           'jspvz/main_image/Zombiez/Zombiez-22.png',
                           'jspvz/main_image/Zombiez/Zombiez-23.png',
                           'jspvz/main_image/Zombiez/Zombiez-24.png',
                           'jspvz/main_image/Zombiez/Zombiez-25.png',
                           'jspvz/main_image/Zombiez/Zombiez-26.png',
                           'jspvz/main_image/Zombiez/Zombiez-27.png',
                           'jspvz/main_image/Zombiez/Zombiez-28.png',
                           'jspvz/main_image/Zombiez/Zombiez-29.png',
                           'jspvz/main_image/Zombiez/Zombiez-30.png',
                           'jspvz/main_image/Zombiez/Zombiez-31.png'
                           ]
        #向日葵
        self.SunFlower_list=['jspvz/main_image/SunFlower1/SunFlower1-1.png',
                             'jspvz/main_image/SunFlower1/SunFlower1-2.png',
                             'jspvz/main_image/SunFlower1/SunFlower1-3.png',
                             'jspvz/main_image/SunFlower1/SunFlower1-4.png',
                             'jspvz/main_image/SunFlower1/SunFlower1-5.png',
                             'jspvz/main_image/SunFlower1/SunFlower1-6.png',
                             'jspvz/main_image/SunFlower1/SunFlower1-7.png',
                             'jspvz/main_image/SunFlower1/SunFlower1-8.png',
                             'jspvz/main_image/SunFlower1/SunFlower1-9.png',
                             'jspvz/main_image/SunFlower1/SunFlower1-10.png',
                             'jspvz/main_image/SunFlower1/SunFlower1-11.png',
                             'jspvz/main_image/SunFlower1/SunFlower1-12.png',
                             'jspvz/main_image/SunFlower1/SunFlower1-13.png',
                             'jspvz/main_image/SunFlower1/SunFlower1-14.png',
                             'jspvz/main_image/SunFlower1/SunFlower1-15.png',
                             'jspvz/main_image/SunFlower1/SunFlower1-16.png',
                             'jspvz/main_image/SunFlower1/SunFlower1-17.png',
                             'jspvz/main_image/SunFlower1/SunFlower1-18.png'
                             ]
        #豌豆
        self.Peashooter_list=[ 'jspvz/main_image/Peashooter/Peashooter-1.png',
                               'jspvz/main_image/Peashooter/Peashooter-2.png',
                               'jspvz/main_image/Peashooter/Peashooter-3.png',
                               'jspvz/main_image/Peashooter/Peashooter-4.png',
                               'jspvz/main_image/Peashooter/Peashooter-5.png',
                               'jspvz/main_image/Peashooter/Peashooter-6.png',
                               'jspvz/main_image/Peashooter/Peashooter-7.png',
                               'jspvz/main_image/Peashooter/Peashooter-8.png',
                               'jspvz/main_image/Peashooter/Peashooter-9.png',
                               'jspvz/main_image/Peashooter/Peashooter-10.png',
                               'jspvz/main_image/Peashooter/Peashooter-11.png',
                               'jspvz/main_image/Peashooter/Peashooter-12.png',
                               'jspvz/main_image/Peashooter/Peashooter-13.png',]
        #轻装僵尸死亡
        self.ZombieDie_list=[ 'jspvz/main_image/ZombieDie/ZombieDie-1.png',
                              'jspvz/main_image/ZombieDie/ZombieDie-2.png',
                              'jspvz/main_image/ZombieDie/ZombieDie-3.png',
                              'jspvz/main_image/ZombieDie/ZombieDie-4.png',
                              'jspvz/main_image/ZombieDie/ZombieDie-5.png',
                              'jspvz/main_image/ZombieDie/ZombieDie-6.png',
                              'jspvz/main_image/ZombieDie/ZombieDie-7.png',
                              'jspvz/main_image/ZombieDie/ZombieDie-8.png',
                              'jspvz/main_image/ZombieDie/ZombieDie-9.png',
                              'jspvz/main_image/ZombieDie/ZombieDie-10.png',
                              ]
        #轻装僵尸吃植物
        self.ZombieAttack_list=['jspvz/main_image/ZombieAttack/ZombieAttack-1.png',
                                'jspvz/main_image/ZombieAttack/ZombieAttack-2.png',
                                'jspvz/main_image/ZombieAttack/ZombieAttack-3.png',
                                'jspvz/main_image/ZombieAttack/ZombieAttack-4.png',
                                'jspvz/main_image/ZombieAttack/ZombieAttack-5.png',
                                'jspvz/main_image/ZombieAttack/ZombieAttack-6.png',
                                'jspvz/main_image/ZombieAttack/ZombieAttack-7.png',
                                'jspvz/main_image/ZombieAttack/ZombieAttack-8.png',
                                'jspvz/main_image/ZombieAttack/ZombieAttack-9.png',
                                'jspvz/main_image/ZombieAttack/ZombieAttack-10.png',
                                'jspvz/main_image/ZombieAttack/ZombieAttack-11.png',
                                'jspvz/main_image/ZombieAttack/ZombieAttack-12.png',
                                'jspvz/main_image/ZombieAttack/ZombieAttack-13.png',
                                'jspvz/main_image/ZombieAttack/ZombieAttack-14.png',
                                'jspvz/main_image/ZombieAttack/ZombieAttack-15.png',
                                'jspvz/main_image/ZombieAttack/ZombieAttack-16.png',
                                'jspvz/main_image/ZombieAttack/ZombieAttack-17.png',
                                'jspvz/main_image/ZombieAttack/ZombieAttack-18.png',
                                'jspvz/main_image/ZombieAttack/ZombieAttack-19.png',
                                'jspvz/main_image/ZombieAttack/ZombieAttack-20.png',
                                'jspvz/main_image/ZombieAttack/ZombieAttack-21.png'
                                ]
        #重装僵尸
        self.FootballZombie_list=['jspvz/main_image/FootballZombie/FootballZombie-1.png',
                                  'jspvz/main_image/FootballZombie/FootballZombie-2.png',
                                  'jspvz/main_image/FootballZombie/FootballZombie-3.png',
                                  'jspvz/main_image/FootballZombie/FootballZombie-4.png',
                                  'jspvz/main_image/FootballZombie/FootballZombie-5.png',
                                  'jspvz/main_image/FootballZombie/FootballZombie-6.png',
                                  'jspvz/main_image/FootballZombie/FootballZombie-7.png',
                                  'jspvz/main_image/FootballZombie/FootballZombie-8.png',
                                  'jspvz/main_image/FootballZombie/FootballZombie-9.png',
                                  'jspvz/main_image/FootballZombie/FootballZombie-10.png',
                                  'jspvz/main_image/FootballZombie/FootballZombie-11.png'
                                  ]
        self.FootballZombieAttack_list=['jspvz/main_image/FootballZombieAttack/FootballZombieAttack-1.png',
                                   'jspvz/main_image/FootballZombieAttack/FootballZombieAttack-2.png',
                                   'jspvz/main_image/FootballZombieAttack/FootballZombieAttack-3.png',
                                   'jspvz/main_image/FootballZombieAttack/FootballZombieAttack-4.png',
                                   'jspvz/main_image/FootballZombieAttack/FootballZombieAttack-5.png',
                                   'jspvz/main_image/FootballZombieAttack/FootballZombieAttack-6.png',
                                   'jspvz/main_image/FootballZombieAttack/FootballZombieAttack-7.png',
                                   'jspvz/main_image/FootballZombieAttack/FootballZombieAttack-8.png',
                                   'jspvz/main_image/FootballZombieAttack/FootballZombieAttack-9.png',
                                   'jspvz/main_image/FootballZombieAttack/FootballZombieAttack-10.png'
                                   ]
        #重装僵尸死亡
        self.FootballZombieDie=['jspvz/main_image/Die/Die-1.png',
                                'jspvz/main_image/Die/Die-2.png',
                                'jspvz/main_image/Die/Die-3.png',
                                'jspvz/main_image/Die/Die-4.png',
                                'jspvz/main_image/Die/Die-5.png',
                                'jspvz/main_image/Die/Die-6.png',
                                'jspvz/main_image/Die/Die-7.png'
                                ]

